"""
This type stub file was generated by pyright.
"""

"""
Functions which are common and """
__all__ = ['central_diff_weights', 'derivative', 'ascent', 'face', 'electrocardiogram']
def central_diff_weights(Np, ndiv=...):
    """
    Return weights for an Np-po"""
    ...

def derivative(func, x0, dx=..., n=..., args=..., order=...):
    """
    Find the nth derivative of """
    ...

def ascent(): # -> ndarray[Unknown, Unknown]:
    """
    Get an 8-bit grayscale bit-"""
    ...

def face(gray=...):
    """
    Get a 1024 x 768, color ima"""
    ...

def electrocardiogram():
    """
    Load an electrocardiogram a"""
    ...

