"""
This type stub file was generated by pyright.
"""

import numpy as np

''' Utilities to allow inserting do'''
__all__ = ['docformat', 'inherit_docstring_from', 'indentcount_lines', 'filldoc', 'unindent_dict', 'unindent_string']
@np.deprecate(message="scipy.misc.docformat is deprecat")
def docformat(docstring, docdict=...):
    ...

@np.deprecate(message="scipy.misc.inherit_docstring_fro" "in SciPy 1.3.0")
def inherit_docstring_from(cls): # -> (func: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.extend_notes_in_docst" "in SciPy 1.3.0")
def extend_notes_in_docstring(cls, notes): # -> (func: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.replace_notes_in_docs" "in SciPy 1.3.0")
def replace_notes_in_docstring(cls, notes): # -> (func: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.indentcount_lines is " "in SciPy 1.3.0")
def indentcount_lines(lines): # -> int:
    ...

@np.deprecate(message="scipy.misc.filldoc is deprecated")
def filldoc(docdict, unindent_params=...): # -> (f: Unknown) -> Unknown:
    ...

@np.deprecate(message="scipy.misc.unindent_dict is depr")
def unindent_dict(docdict): # -> dict[Unknown, Unknown]:
    ...

@np.deprecate(message="scipy.misc.unindent_string is de")
def unindent_string(docstring): # -> str:
    ...

