"""
This type stub file was generated by pyright.
"""

"""
Discrete Fourier Transforms - b"""
__all__ = ['fft', 'ifft', 'fftn', 'ifftn', 'rfft', 'irfft', 'fft2', 'ifft2']
def fft(x, n=..., axis=..., overwrite_x=...): # -> Any:
    """
    Return discrete Fourier tra"""
    ...

def ifft(x, n=..., axis=..., overwrite_x=...): # -> Any:
    """
    Return discrete inverse Fou"""
    ...

def rfft(x, n=..., axis=..., overwrite_x=...): # -> Any:
    """
    Discrete Fourier transform """
    ...

def irfft(x, n=..., axis=..., overwrite_x=...): # -> Any:
    """
    Return inverse discrete Fou"""
    ...

def fftn(x, shape=..., axes=..., overwrite_x=...): # -> Any:
    """
    Return multidimensional dis"""
    ...

def ifftn(x, shape=..., axes=..., overwrite_x=...): # -> Any:
    """
    Return inverse multidimensi"""
    ...

def fft2(x, shape=..., axes=..., overwrite_x=...): # -> Any:
    """
    2-D discrete Fourier transf"""
    ...

def ifft2(x, shape=..., axes=..., overwrite_x=...): # -> Any:
    """
    2-D discrete inverse Fourie"""
    ...

