"""
This type stub file was generated by pyright.
"""

__all__ = ['fftshift', 'ifftshift', 'fftfreq', 'rfftfreq', 'next_fast_len']
def rfftfreq(n, d=...):
    """DFT sample frequencies (for usag"""
    ...

def next_fast_len(target):
    """
    Find the next fast size of """
    ...

