"""
This type stub file was generated by pyright.
"""

"""
Differential and pseudo-differe"""
__all__ = ['diff', 'tilbert', 'itilbert', 'hilbert', 'ihilbert', 'cs_diff', 'cc_diff', 'sc_diff', 'ss_diff', 'shift']
_cache = ...
def diff(x, order=..., period=..., _cache=...): # -> ndarray[Unknown, Unknown] | Any:
    """
    Return kth derivative (or i"""
    ...

_cache = ...
def tilbert(x, h, period=..., _cache=...): # -> Any:
    """
    Return h-Tilbert transform """
    ...

_cache = ...
def itilbert(x, h, period=..., _cache=...): # -> Any:
    """
    Return inverse h-Tilbert tr"""
    ...

_cache = ...
def hilbert(x, _cache=...): # -> Any:
    """
    Return Hilbert transform of"""
    ...

def ihilbert(x): # -> Any:
    """
    Return inverse Hilbert tran"""
    ...

_cache = ...
def cs_diff(x, a, b, period=..., _cache=...): # -> Any:
    """
    Return (a,b)-cosh/sinh pseu"""
    ...

_cache = ...
def sc_diff(x, a, b, period=..., _cache=...): # -> Any:
    """
    Return (a,b)-sinh/cosh pseu"""
    ...

_cache = ...
def ss_diff(x, a, b, period=..., _cache=...): # -> Any:
    """
    Return (a,b)-sinh/sinh pseu"""
    ...

_cache = ...
def cc_diff(x, a, b, period=..., _cache=...): # -> Any:
    """
    Return (a,b)-cosh/cosh pseu"""
    ...

_cache = ...
def shift(x, a, period=..., _cache=...): # -> Any:
    """
    Shift periodic sequence x b"""
    ...

