"""
This type stub file was generated by pyright.
"""

"""
Real spectrum transforms (DCT, """
__all__ = ['dct', 'idct', 'dst', 'idst', 'dctn', 'idctn', 'dstn', 'idstn']
_inverse_typemap = ...
def dctn(x, type=..., shape=..., axes=..., norm=..., overwrite_x=...):
    """
    Return multidimensional Dis"""
    ...

def idctn(x, type=..., shape=..., axes=..., norm=..., overwrite_x=...):
    """
    Return multidimensional Dis"""
    ...

def dstn(x, type=..., shape=..., axes=..., norm=..., overwrite_x=...):
    """
    Return multidimensional Dis"""
    ...

def idstn(x, type=..., shape=..., axes=..., norm=..., overwrite_x=...):
    """
    Return multidimensional Dis"""
    ...

def dct(x, type=..., n=..., axis=..., norm=..., overwrite_x=...):
    r"""
    Return the Discrete Cosine """
    ...

def idct(x, type=..., n=..., axis=..., norm=..., overwrite_x=...):
    """
    Return the Inverse Discrete"""
    ...

def dst(x, type=..., n=..., axis=..., norm=..., overwrite_x=...):
    r"""
    Return the Discrete Sine Tr"""
    ...

def idst(x, type=..., n=..., axis=..., norm=..., overwrite_x=...):
    """
    Return the Inverse Discrete"""
    ...

