"""
This type stub file was generated by pyright.
"""

from .lobpcg import *
from scipy._lib._testutils import PytestTester

"""
Locally Optimal Block Precondit"""
__all__ = [s for s in dir() if nots.startswith('_')]
test = ...
