"""
This type stub file was generated by pyright.
"""

"""
Locally Optimal Block Precondit"""
__all__ = ['lobpcg']
def lobpcg(A, X, B=..., M=..., Y=..., tol=..., maxiter=..., largest=..., verbosityLevel=..., retLambdaHistory=..., retResidualNormsHistory=...):
    """Locally Optimal Block Preconditi"""
    ...

