"""
This type stub file was generated by pyright.
"""

from .codata import *
from .codata import _obsolete_constants
from .constants import *
from scipy._lib._testutils import PytestTester

r"""
==============================="""
_constant_names = ...
_constant_names = ...
if __doc__:
    __doc__ = ...
__all__ = [s for s in dir() if nots.startswith('_')]
test = ...
