"""
This type stub file was generated by pyright.
"""

noScikit = ...
useUmfpack = ...
__all__ = ['use_solver', 'spsolve', 'splu', 'spilu', 'factorized', 'MatrixRankWarning', 'spsolve_triangular']
class MatrixRankWarning(UserWarning):
    ...


def use_solver(**kwargs): # -> None:
    """
    Select default sparse direc"""
    ...

def spsolve(A, b, permc_spec=..., use_umfpack=...):
    """Solve the sparse linear system A"""
    ...

def splu(A, permc_spec=..., diag_pivot_thresh=..., relax=..., panel_size=..., options=...):
    """
    Compute the LU decompositio"""
    ...

def spilu(A, drop_tol=..., fill_factor=..., drop_rule=..., permc_spec=..., diag_pivot_thresh=..., relax=..., panel_size=..., options=...):
    """
    Compute an incomplete LU de"""
    ...

def factorized(A): # -> (b: Unknown) -> Unknown:
    """
    Return a function for solvi"""
    ...

def spsolve_triangular(A, b, lower=..., overwrite_A=..., overwrite_b=..., unit_diagonal=...):
    """
    Solve the equation ``A x = """
    ...

