"""
This type stub file was generated by pyright.
"""

from .interpolate import *
from .fitpack import *
from .fitpack2 import *
from .rbf import Rbf
from ._rbfinterp import *
from .polyint import *
from ._cubic import *
from .ndgriddata import *
from ._bsplines import *
from ._pade import *
from scipy._lib._testutils import PytestTester

"""
==============================="""
__all__ = [s for s in dir() if nots.startswith('_')]
test = ...
pchip = PchipInterpolator
