"""
This type stub file was generated by pyright.
"""

def linear(r):
    ...

def thin_plate_spline(r): # -> float:
    ...

def cubic(r):
    ...

def quintic(r):
    ...

def multiquadric(r): # -> Any:
    ...

def inverse_multiquadric(r): # -> Any:
    ...

def inverse_quadratic(r):
    ...

def gaussian(r): # -> Any:
    ...

NAME_TO_FUNC = ...
def kernel_vector(x, y, kernel_func, out): # -> None:
    """Evaluate RBFs, with centers at `"""
    ...

def polynomial_vector(x, powers, out): # -> None:
    """Evaluate monomials, with exponen"""
    ...

def kernel_matrix(x, kernel_func, out): # -> None:
    """Evaluate RBFs, with centers at `"""
    ...

def polynomial_matrix(x, powers, out): # -> None:
    """Evaluate monomials, with exponen"""
    ...

