"""
This type stub file was generated by pyright.
"""

"""Module for RBF interpolation."""
__all__ = ["RBFInterpolator"]
_AVAILABLE = ...
_SCALE_INVARIANT = ...
_NAME_TO_MIN_DEGREE = ...
class RBFInterpolator:
    """Radial basis function (RBF) inte"""
    def __init__(self, y, d, neighbors=..., smoothing=..., kernel=..., epsilon=..., degree=...) -> None:
        ...
    
    def __call__(self, x): # -> ndarray[Any, dtype[Any]]:
        """Evaluate the interpolant at `x`."""
        ...
    


