"""
This type stub file was generated by pyright.
"""

__all__ = ['splrep', 'splprep', 'splev', 'splint', 'sproot', 'spalde', 'bisplrep', 'bisplev', 'insert', 'splder', 'splantider']
def splprep(x, w=..., u=..., ub=..., ue=..., k=..., task=..., s=..., t=..., full_output=..., nest=..., per=..., quiet=...):
    """
    Find the B-spline represent"""
    ...

def splrep(x, y, w=..., xb=..., xe=..., k=..., task=..., s=..., t=..., full_output=..., per=..., quiet=...):
    """
    Find the B-spline represent"""
    ...

def splev(x, tck, der=..., ext=...): # -> ndarray[Any, Unknown] | list[Unknown] | Any:
    """
    Evaluate a B-spline or its """
    ...

def splint(a, b, tck, full_output=...): # -> list[Unknown] | tuple[Any, Any] | Any:
    """
    Evaluate the definite integ"""
    ...

def sproot(tck, mest=...): # -> list[Unknown] | Any:
    """
    Find the roots of a cubic B"""
    ...

def spalde(x, tck): # -> list[Unknown] | Any:
    """
    Evaluate all derivatives of"""
    ...

def insert(x, tck, m=..., per=...): # -> BSpline | tuple[Unbound | Unknown, list[Unknown], Unbound | Unknown] | tuple[Any, Any, Unknown]:
    """
    Insert knots into a B-splin"""
    ...

def splder(tck, n=...): # -> BSpline | tuple[Unknown | Any, Unknown | Any, Unknown] | tuple[Unknown, Unknown | Any, Unknown]:
    """
    Compute the spline represen"""
    ...

def splantider(tck, n=...): # -> BSpline | tuple[Unknown | Any, Unknown | Any, Unknown] | tuple[Unknown, Unknown | Any, Unknown]:
    """
    Compute the spline for the """
    ...

