"""
This type stub file was generated by pyright.
"""

"""rbf - Radial basis functions for"""
__all__ = ['Rbf']
class Rbf:
    """
    Rbf(*args)

    A class for"""
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def A(self): # -> Any:
        ...
    
    def __call__(self, *args):
        ...
    


