"""
This type stub file was generated by pyright.
"""

def ellip_harm(h2, k2, n, p, s, signm=..., signn=...): # -> Any:
    r"""
    Ellipsoidal harmonic functi"""
    ...

_ellip_harm_2_vec = ...
def ellip_harm_2(h2, k2, n, p, s): # -> Any:
    r"""
    Ellipsoidal harmonic functi"""
    ...

_ellip_normal_vec = ...
def ellip_normal(h2, k2, n, p):
    r"""
    Ellipsoidal harmonic normal"""
    ...

