"""
This type stub file was generated by pyright.
"""

__all__ = ["logsumexp", "softmax", "log_softmax"]
def logsumexp(a, axis=..., b=..., keepdims=..., return_sign=...):
    """Compute the log of the sum of ex"""
    ...

def softmax(x, axis=...): # -> Any:
    r"""
    Softmax function

    The s"""
    ...

def log_softmax(x, axis=...): # -> Any:
    r"""
    Logarithm of softmax functi"""
    ...

