"""
This type stub file was generated by pyright.
"""

def spherical_jn(n, z, derivative=...): # -> Any:
    r"""Spherical Bessel function of the"""
    ...

def spherical_yn(n, z, derivative=...): # -> Any:
    r"""Spherical Bessel function of the"""
    ...

def spherical_in(n, z, derivative=...): # -> Any:
    r"""Modified spherical Bessel functi"""
    ...

def spherical_kn(n, z, derivative=...): # -> Any:
    r"""Modified spherical Bessel functi"""
    ...

