"""
This type stub file was generated by pyright.
"""

"""Warnings and Exceptions that can"""
class SpecialFunctionWarning(Warning):
    """Warning that can be emitted by s"""
    ...


class SpecialFunctionError(Exception):
    """Exception that can be raised by """
    ...


