"""
This type stub file was generated by pyright.
"""

from .mio import loadmat, savemat, whosmat
from . import byteordercodes
from scipy._lib._testutils import PytestTester

"""
Utilities for dealing with MATL"""
__all__ = ['loadmat', 'savemat', 'whosmat', 'byteordercodes']
test = ...
