"""
This type stub file was generated by pyright.
"""

import contextlib

_config = ...
_cpu_count = ...
_NORM_MAP = ...
@contextlib.contextmanager
def set_workers(workers): # -> Generator[None, None, None]:
    """Context manager for the default """
    ...

def get_workers(): # -> Any | int:
    """Returns the default number of wo"""
    ...

