"""
This type stub file was generated by pyright.
"""

"""
Functions for acting on a axis """
def axis_slice(a, start=..., stop=..., step=..., axis=...):
    """Take a slice along axis 'axis' f"""
    ...

def axis_reverse(a, axis=...):
    """Reverse the 1-D slices of `a` al"""
    ...

def odd_ext(x, n, axis=...):
    """
    Odd extension at the bounda"""
    ...

def even_ext(x, n, axis=...):
    """
    Even extension at the bound"""
    ...

def const_ext(x, n, axis=...):
    """
    Constant extension at the b"""
    ...

def zero_ext(x, n, axis=...):
    """
    Zero padding at the boundar"""
    ...

