"""
This type stub file was generated by pyright.
"""

"""Tools for MLS generation"""
__all__ = ['max_len_seq']
_mls_taps = ...
def max_len_seq(nbits, state=..., length=..., taps=...): # -> tuple[ndarray[Unknown, Unknown], Unknown]:
    """
    Maximum length sequence (ML"""
    ...

