"""
This type stub file was generated by pyright.
"""

"""
Functions for identifying peaks"""
__all__ = ['argrelmin', 'argrelmax', 'argrelextrema', 'peak_prominences', 'peak_widths', 'find_peaks', 'find_peaks_cwt']
def argrelmin(data, axis=..., order=..., mode=...): # -> Tuple[ndarray[Unknown, Unknown], ...]:
    """
    Calculate the relative mini"""
    ...

def argrelmax(data, axis=..., order=..., mode=...): # -> Tuple[ndarray[Unknown, Unknown], ...]:
    """
    Calculate the relative maxi"""
    ...

def argrelextrema(data, comparator, axis=..., order=..., mode=...): # -> Tuple[ndarray[Unknown, Unknown], ...]:
    """
    Calculate the relative extr"""
    ...

def peak_prominences(x, peaks, wlen=...):
    """
    Calculate the prominence of"""
    ...

def peak_widths(x, peaks, rel_height=..., prominence_data=..., wlen=...):
    """
    Calculate the width of each"""
    ...

def find_peaks(x, height=..., threshold=..., distance=..., prominence=..., width=..., wlen=..., rel_height=..., plateau_size=...):
    """
    Find peaks inside a signal """
    ...

def find_peaks_cwt(vector, widths, wavelet=..., max_distances=..., gap_thresh=..., min_length=..., min_snr=..., noise_perc=..., window_size=...): # -> ndarray[Unknown, Unknown]:
    """
    Find peaks in a 1-D array w"""
    ...

