"""
This type stub file was generated by pyright.
"""

def savgol_coeffs(window_length, polyorder, deriv=..., delta=..., pos=..., use=...): # -> ndarray[Unknown, Unknown]:
    """Compute the coefficients for a 1"""
    ...

def savgol_filter(x, window_length, polyorder, deriv=..., delta=..., axis=..., mode=..., cval=...):
    """ Apply a Savitzky-Golay filter t"""
    ...

