"""
This type stub file was generated by pyright.
"""

__all__ = ['upfirdn', '_output_len']
_upfirdn_modes = ...
class _UpFIRDn:
    """Helper for resampling."""
    def __init__(self, h, x_dtype, up, down) -> None:
        ...
    
    def apply_filter(self, x, axis=..., mode=..., cval=...): # -> ndarray[Unknown, Unknown]:
        """Apply the prepared filter to the"""
        ...
    


def upfirdn(h, x, up=..., down=..., axis=..., mode=..., cval=...): # -> ndarray[Unknown, Unknown]:
    """Upsample, FIR filter, and downsa"""
    ...

