"""
This type stub file was generated by pyright.
"""

__all__ = ['spline_filter', 'bspline', 'gauss_spline', 'cubic', 'quadratic', 'cspline1d', 'qspline1d', 'cspline1d_eval', 'qspline1d_eval']
def spline_filter(Iin, lmbda=...): # -> Any:
    """Smoothing spline (cubic) filteri"""
    ...

_splinefunc_cache = ...
def bspline(x, n):
    """B-spline basis function of order"""
    ...

def gauss_spline(x, n): # -> Any:
    r"""Gaussian approximation to B-spli"""
    ...

def cubic(x): # -> NDArray[bool_]:
    """A cubic B-spline.

    This is a"""
    ...

def quadratic(x): # -> NDArray[bool_]:
    """A quadratic B-spline.

    This """
    ...

def cspline1d(signal, lamb=...): # -> ndarray[Unknown, Unknown] | NDArray[floating[Any]]:
    """
    Compute cubic spline coeffi"""
    ...

def qspline1d(signal, lamb=...): # -> NDArray[floating[Any]]:
    """Compute quadratic spline coeffic"""
    ...

def cspline1d_eval(cj, newx, dx=..., x0=...): # -> NDArray[floating[Any]]:
    """Evaluate a cubic spline at the n"""
    ...

def qspline1d_eval(cj, newx, dx=..., x0=...): # -> NDArray[floating[Any]]:
    """Evaluate a quadratic spline at t"""
    ...

