"""
This type stub file was generated by pyright.
"""

"""
ltisys -- a collection of funct"""
__all__ = ['tf2ss', 'abcd_normalize', 'ss2tf', 'zpk2ss', 'ss2zpk', 'cont2discrete']
def tf2ss(num, den): # -> tuple[ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Unknown, Unknown]] | tuple[ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Any, Unknown]] | tuple[Any, ndarray[Any, Any], Any, ndarray[Any, Unknown]]:
    r"""Transfer function to state-space"""
    ...

def abcd_normalize(A=..., B=..., C=..., D=...): # -> tuple[ndarray[Unknown, Unknown] | Unknown, ndarray[Unknown, Unknown] | Unknown, ndarray[Unknown, Unknown] | Unknown, ndarray[Unknown, Unknown] | Unknown]:
    """Check state-space matrices and e"""
    ...

def ss2tf(A, B, C, D, input=...): # -> tuple[ndarray[Unknown, Unknown], Unknown | list[Unknown] | Literal[1]] | tuple[ndarray[Unknown, Unknown], Unknown | Literal[1]]:
    r"""State-space to transfer function"""
    ...

def zpk2ss(z, p, k): # -> tuple[ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Unknown, Unknown]] | tuple[ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Any, Unknown]] | tuple[Any, ndarray[Any, Any], Any, ndarray[Any, Unknown]]:
    """Zero-pole-gain representation to"""
    ...

def ss2zpk(A, B, C, D, input=...): # -> tuple[Unknown, Unknown, Unknown]:
    """State-space representation to ze"""
    ...

def cont2discrete(system, dt, method=..., alpha=...):
    """
    Transform a continuous to a"""
    ...

