"""
This type stub file was generated by pyright.
"""

"""Tools for spectral analysis.
"""
__all__ = ['periodogram', 'welch', 'lombscargle', 'csd', 'coherence', 'spectrogram', 'stft', 'istft', 'check_COLA', 'check_NOLA']
def lombscargle(x, y, freqs, precenter=..., normalize=...): # -> Any:
    """
    lombscargle(x, y, freqs)

 """
    ...

def periodogram(x, fs=..., window=..., nfft=..., detrend=..., return_onesided=..., scaling=..., axis=...): # -> tuple[ndarray[Unknown, Unknown], ndarray[Unknown, Unknown]] | tuple[Unknown, Unknown | ndarray[Unknown, _dtype]]:
    """
    Estimate power spectral den"""
    ...

def welch(x, fs=..., window=..., nperseg=..., noverlap=..., nfft=..., detrend=..., return_onesided=..., scaling=..., axis=..., average=...): # -> tuple[Unknown, Unknown | ndarray[Unknown, _dtype]]:
    r"""
    Estimate power spectral den"""
    ...

def csd(x, y, fs=..., window=..., nperseg=..., noverlap=..., nfft=..., detrend=..., return_onesided=..., scaling=..., axis=..., average=...): # -> tuple[Unknown, Unknown | ndarray[Unknown, Unknown]]:
    r"""
    Estimate the cross power sp"""
    ...

def spectrogram(x, fs=..., window=..., nperseg=..., noverlap=..., nfft=..., detrend=..., return_onesided=..., scaling=..., axis=..., mode=...): # -> tuple[Unknown, Unknown, Unknown | Any]:
    """Compute a spectrogram with conse"""
    ...

def check_COLA(window, nperseg, noverlap, tol=...):
    r"""Check whether the Constant OverL"""
    ...

def check_NOLA(window, nperseg, noverlap, tol=...):
    r"""Check whether the Nonzero Overla"""
    ...

def stft(x, fs=..., window=..., nperseg=..., noverlap=..., nfft=..., detrend=..., return_onesided=..., boundary=..., padded=..., axis=...): # -> tuple[Unknown, Unknown, Unknown]:
    r"""Compute the Short Time Fourier T"""
    ...

def istft(Zxx, fs=..., window=..., nperseg=..., noverlap=..., nfft=..., input_onesided=..., boundary=..., time_axis=..., freq_axis=...):
    r"""Perform the inverse Short Time F"""
    ...

def coherence(x, y, fs=..., window=..., nperseg=..., noverlap=..., nfft=..., detrend=..., axis=...): # -> tuple[Unknown, Unknown | Any]:
    r"""
    Estimate the magnitude squa"""
    ...

