"""
This type stub file was generated by pyright.
"""

__all__ = ['sawtooth', 'square', 'gausspulse', 'chirp', 'sweep_poly', 'unit_impulse']
def sawtooth(t, width=...): # -> ndarray[Unknown, Unknown]:
    """
    Return a periodic sawtooth """
    ...

def square(t, duty=...): # -> ndarray[Unknown, Unknown]:
    """
    Return a periodic square-wa"""
    ...

def gausspulse(t, fc=..., bw=..., bwr=..., tpr=..., retquad=..., retenv=...):
    """
    Return a Gaussian modulated"""
    ...

def chirp(t, f0, t1, f1, method=..., phi=..., vertex_zero=...): # -> Any:
    """Frequency-swept cosine generator"""
    ...

def sweep_poly(t, poly, phi=...): # -> Any:
    """
    Frequency-swept cosine gene"""
    ...

def unit_impulse(shape, idx=..., dtype=...): # -> ndarray[Unknown, Unknown]:
    """
    Unit impulse signal (discre"""
    ...

