"""
This type stub file was generated by pyright.
"""

"""
Disjoint set data structure
"""
class DisjointSet:
    """ Disjoint set data structure for"""
    def __init__(self, elements=...) -> None:
        ...
    
    def __iter__(self): # -> Iterator[Unknown]:
        """Returns an iterator of the eleme"""
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __contains__(self, x): # -> bool:
        ...
    
    def __getitem__(self, x):
        """Find the root element of `x`.

 """
        ...
    
    def add(self, x): # -> None:
        """Add element `x` to disjoint set
"""
        ...
    
    def merge(self, x, y): # -> bool:
        """Merge the subsets of `x` and `y`"""
        ...
    
    def connected(self, x, y):
        """Test whether `x` and `y` are in """
        ...
    
    def subset(self, x): # -> set[Unknown]:
        """Get the subset containing `x`.

"""
        ...
    
    def subsets(self): # -> list[Unknown]:
        """Get all the subsets in the disjo"""
        ...
    


