"""
This type stub file was generated by pyright.
"""

"""
Generic test utilities.

"""
__all__ = ['PytestTester', 'check_free_memory']
class FPUModeChangeWarning(RuntimeWarning):
    """Warning about FPU mode change"""
    ...


class PytestTester:
    """
    Pytest test runner entry po"""
    def __init__(self, module_name) -> None:
        ...
    
    def __call__(self, label=..., verbose=..., extra_argv=..., doctests=..., coverage=..., tests=..., parallel=...):
        ...
    


def check_free_memory(free_mb): # -> None:
    """
    Check *free_mb* of memory i"""
    ...

