"""
This type stub file was generated by pyright.
"""

__all__ = ['ReentrancyError', 'ReentrancyLock', 'non_reentrant']
class ReentrancyError(RuntimeError):
    ...


class ReentrancyLock:
    """
    Threading lock that raises """
    def __init__(self, err_msg) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, type, value, traceback): # -> None:
        ...
    
    def decorate(self, func): # -> Any:
        ...
    


def non_reentrant(err_msg=...): # -> (func: Unknown) -> (Unknown | Any):
    """
    Decorate a function with a """
    ...

