"""
This type stub file was generated by pyright.
"""

__all__ = ["_deprecated"]
class _DeprecationHelperStr:
    """
    Helper class used by deprec"""
    def __init__(self, content, message) -> None:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


def deprecate_cython_api(module, routine_name, new_name=..., message=...): # -> None:
    """
    Deprecate an exported cdef """
    ...

