"""
This type stub file was generated by pyright.
"""

''' Utilities to allow inserting do'''
__all__ = ['docformat', 'inherit_docstring_from', 'indentcount_lines', 'filldoc', 'unindent_dict', 'unindent_string', 'doc_replace']
def docformat(docstring, docdict=...):
    ''' Fill a function docstring from '''
    ...

def inherit_docstring_from(cls): # -> (func: Unknown) -> Unknown:
    """
    This decorator modifies the"""
    ...

def extend_notes_in_docstring(cls, notes): # -> (func: Unknown) -> Unknown:
    """
    This decorator replaces the"""
    ...

def replace_notes_in_docstring(cls, notes): # -> (func: Unknown) -> Unknown:
    """
    This decorator replaces the"""
    ...

def indentcount_lines(lines): # -> int:
    ''' Minimum indent for all lines in'''
    ...

def filldoc(docdict, unindent_params=...): # -> (f: Unknown) -> Unknown:
    ''' Return docstring decorator usin'''
    ...

def unindent_dict(docdict): # -> dict[Unknown, Unknown]:
    ''' Unindent all strings in a docdi'''
    ...

def unindent_string(docstring): # -> str:
    ''' Set docstring to minimum indent'''
    ...

def doc_replace(obj, oldval, newval): # -> (func: Unknown) -> Unknown:
    """Decorator to take the docstring """
    ...

