"""
This type stub file was generated by pyright.
"""

from .matlab import byteordercodes, loadmat, savemat, whosmat
from .netcdf import netcdf_file, netcdf_variable
from ._fortran import FortranEOFError, FortranFile, FortranFormattingError
from .mmio import mminfo, mmread, mmwrite
from .idl import readsav
from .harwell_boeing import hb_read, hb_write
from scipy._lib._testutils import PytestTester

u"""
==============================="""
__all__ = [s for s in dir() if nots.startswith('_')]
test = ...
