"""
This type stub file was generated by pyright.
"""

__all__ = ['readsav']
DTYPE_DICT = ...
RECTYPE_DICT = ...
STRUCT_DICT = ...
class Pointer:
    '''Class used to define pointers'''
    def __init__(self, index) -> None:
        ...
    


class ObjectPointer(Pointer):
    '''Class used to define object poin'''
    ...


class AttrDict(dict):
    '''
    A case-insensitive dictiona'''
    def __init__(self, init=...) -> None:
        ...
    
    def __getitem__(self, name):
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    __getattr__ = ...
    __setattr__ = ...
    __call__ = ...


def readsav(file_name, idict=..., python_dict=..., uncompressed_file_name=..., verbose=...):
    """
    Read an IDL .sav file.

   """
    ...

