"""
This type stub file was generated by pyright.
"""

"""Indexing mixin for sparse matrix"""
class IndexMixin:
    """
    This class provides common """
    def __getitem__(self, key):
        ...
    
    def __setitem__(self, key, x):
        ...
    
    def getrow(self, i):
        """Return a copy of row i of the ma"""
        ...
    
    def getcol(self, i):
        """Return a copy of column i of the"""
        ...
    


