"""
This type stub file was generated by pyright.
"""

__all__ = ['save_npz', 'load_npz']
PICKLE_KWARGS = ...
def save_npz(file, matrix, compressed=...): # -> None:
    """ Save a sparse matrix to a file """
    ...

def load_npz(file): # -> Any:
    """ Load a sparse matrix from a fil"""
    ...

