"""
This type stub file was generated by pyright.
"""

from .data import _data_matrix, _minmax_mixin

""" A sparse matrix in COOrdinate o"""
__docformat__ = ...
__all__ = ['coo_matrix', 'isspmatrix_coo']
class coo_matrix(_data_matrix, _minmax_mixin):
    """
    A sparse matrix in COOrdina"""
    format = ...
    def __init__(self, arg1, shape=..., dtype=..., copy=...) -> None:
        ...
    
    def reshape(self, *args, **kwargs): # -> Self@coo_matrix | coo_matrix:
        ...
    
    def getnnz(self, axis=...): # -> int | tuple[Unknown, Unknown | None]:
        ...
    
    def transpose(self, axes=..., copy=...): # -> coo_matrix:
        ...
    
    def resize(self, *shape): # -> None:
        ...
    
    def toarray(self, order=..., out=...): # -> ndarray[Unknown, Unknown]:
        """See the docstring for `spmatrix."""
        ...
    
    def tocsc(self, copy=...): # -> csc_matrix:
        """Convert this matrix to Compresse"""
        ...
    
    def tocsr(self, copy=...): # -> csr_matrix:
        """Convert this matrix to Compresse"""
        ...
    
    def tocoo(self, copy=...): # -> Self@coo_matrix:
        ...
    
    def todia(self, copy=...): # -> dia_matrix:
        ...
    
    def todok(self, copy=...): # -> dok_matrix:
        ...
    
    def diagonal(self, k=...): # -> ndarray[Unknown, Unknown]:
        ...
    
    def sum_duplicates(self): # -> None:
        """Eliminate duplicate matrix entri"""
        ...
    
    def eliminate_zeros(self): # -> None:
        """Remove zero entries from the mat"""
        ...
    


def isspmatrix_coo(x): # -> bool:
    """Is x of coo_matrix type?

    Pa"""
    ...

