"""
This type stub file was generated by pyright.
"""

from .compressed import _cs_matrix

"""Compressed Sparse Column matrix """
__docformat__ = ...
__all__ = ['csc_matrix', 'isspmatrix_csc']
class csc_matrix(_cs_matrix):
    """
    Compressed Sparse Column ma"""
    format = ...
    def transpose(self, axes=..., copy=...): # -> csr_matrix:
        ...
    
    def __iter__(self): # -> Generator[csr_matrix, None, None]:
        ...
    
    def tocsc(self, copy=...): # -> Self@csc_matrix:
        ...
    
    def tocsr(self, copy=...): # -> csr_matrix:
        ...
    
    def nonzero(self): # -> tuple[Any | Unknown, Any]:
        ...
    
    def getrow(self, i):
        """Returns a copy of row i of the m"""
        ...
    
    def getcol(self, i):
        """Returns a copy of column i of th"""
        ...
    


def isspmatrix_csc(x): # -> bool:
    """Is x of csc_matrix type?

    Pa"""
    ...

