"""
This type stub file was generated by pyright.
"""

from .compressed import _cs_matrix

"""Compressed Sparse Row matrix for"""
__docformat__ = ...
__all__ = ['csr_matrix', 'isspmatrix_csr']
class csr_matrix(_cs_matrix):
    """
    Compressed Sparse Row matri"""
    format = ...
    def transpose(self, axes=..., copy=...): # -> csc_matrix:
        ...
    
    def tolil(self, copy=...): # -> lil_matrix:
        ...
    
    def tocsr(self, copy=...): # -> Self@csr_matrix:
        ...
    
    def tocsc(self, copy=...): # -> csc_matrix:
        ...
    
    def tobsr(self, blocksize=..., copy=...): # -> bsr_matrix:
        ...
    
    def __iter__(self): # -> Generator[csr_matrix, None, None]:
        ...
    
    def getrow(self, i): # -> csr_matrix:
        """Returns a copy of row i of the m"""
        ...
    
    def getcol(self, i): # -> csr_matrix:
        """Returns a copy of column i of th"""
        ...
    


def isspmatrix_csr(x): # -> bool:
    """Is x of csr_matrix type?

    Pa"""
    ...

