"""
This type stub file was generated by pyright.
"""

from .data import _data_matrix

"""Sparse DIAgonal format"""
__docformat__ = ...
__all__ = ['dia_matrix', 'isspmatrix_dia']
class dia_matrix(_data_matrix):
    """Sparse matrix with DIAgonal stor"""
    format = ...
    def __init__(self, arg1, shape=..., dtype=..., copy=...) -> None:
        ...
    
    def __repr__(self): # -> Any:
        ...
    
    def count_nonzero(self): # -> int:
        ...
    
    def getnnz(self, axis=...): # -> int:
        ...
    
    def sum(self, axis=..., dtype=..., out=...):
        ...
    
    def todia(self, copy=...): # -> Self@dia_matrix:
        ...
    
    def transpose(self, axes=..., copy=...): # -> dia_matrix:
        ...
    
    def diagonal(self, k=...): # -> ndarray[Unknown, Unknown] | Any:
        ...
    
    def tocsc(self, copy=...): # -> csc_matrix:
        ...
    
    def tocoo(self, copy=...): # -> coo_matrix:
        ...
    
    def resize(self, *shape): # -> None:
        ...
    


def isspmatrix_dia(x): # -> bool:
    """Is x of dia_matrix type?

    Pa"""
    ...

