"""
This type stub file was generated by pyright.
"""

"""Functions to extract parts of sp"""
__docformat__ = ...
__all__ = ['find', 'tril', 'triu']
def find(A): # -> tuple[Any | Unknown, Any | Unknown, Any | Unknown]:
    """Return the indices and values of"""
    ...

def tril(A, k=..., format=...): # -> coo_matrix | Any:
    """Return the lower triangular port"""
    ...

def triu(A, k=..., format=...): # -> coo_matrix | Any:
    """Return the upper triangular port"""
    ...

