"""
This type stub file was generated by pyright.
"""

__all__ = ['needs_g77_abi_wrapper', 'get_g77_abi_wrappers', 'gfortran_legacy_flag_hook', 'blas_ilp64_pre_build_hook', 'get_f2py_int64_options', 'generic_pre_build_hook', 'write_file_content', 'ilp64_pre_build_hook']
def get_fcompiler_ilp64_flags(): # -> dict[str, list[str]]:
    """
    Dictionary of compiler flag"""
    ...

def get_fcompiler_macro_include_flags(path): # -> dict[str, list[str | Unknown]]:
    """
    Dictionary of compiler flag"""
    ...

def uses_mkl(info): # -> bool:
    ...

def needs_g77_abi_wrapper(info): # -> bool:
    """Returns True if g77 ABI wrapper """
    ...

def get_g77_abi_wrappers(info): # -> list[Unknown]:
    """
    Returns file names of sourc"""
    ...

def gfortran_legacy_flag_hook(cmd, ext): # -> None:
    """
    Pre-build hook to add dd gf"""
    ...

def get_f2py_int64_options(): # -> list[str]:
    ...

def ilp64_pre_build_hook(cmd, ext): # -> None:
    """
    Pre-build hook for adding F"""
    ...

def blas_ilp64_pre_build_hook(blas_info): # -> (cmd: Unknown, ext: Unknown) -> None:
    """
    Pre-build hook for adding I"""
    ...

def generic_pre_build_hook(cmd, ext, fcompiler_flags, patch_source_func=..., source_fnpart=...): # -> None:
    """
    Pre-build hook for adding c"""
    ...

def write_file_content(filename, content): # -> None:
    """
    Write content to file, but """
    ...

def get_blas_lapack_symbols(): # -> Any | tuple[Unknown, ...]:
    ...

