"""
This type stub file was generated by pyright.
"""

"""
Helpers for detection of compil"""
def try_compile(compiler, code=..., flags=..., ext=...): # -> bool:
    """Returns True if the compiler is """
    ...

def has_flag(compiler, flag, ext=...): # -> bool:
    """Returns True if the compiler sup"""
    ...

def get_cxx_std_flag(compiler): # -> str | None:
    """Detects compiler flag for c++14,"""
    ...

def get_c_std_flag(compiler): # -> str | None:
    """Detects compiler flag to enable """
    ...

def try_add_flag(args, compiler, flag, ext=...): # -> None:
    """Appends flag to the list of argu"""
    ...

def set_c_flags_hook(build_ext, ext): # -> None:
    """Sets basic compiler flags for co"""
    ...

def set_cxx_flags_hook(build_ext, ext): # -> None:
    """Sets basic compiler flags for co"""
    ...

def set_cxx_flags_clib_hook(build_clib, build_info): # -> None:
    ...

