"""
This type stub file was generated by pyright.
"""

import numpy as np
from numpy.distutils.system_info import BlasNotFoundError, LapackNotFoundError, system_info
from scipy._lib import _pep440

def combine_dict(*dicts, **kw): # -> dict[Unknown, Unknown]:
    """
    Combine Numpy distutils sty"""
    ...

if _pep440.parse(np.__version__) >= _pep440.Version("1.15.0.dev"):
    get_info = ...
else:
    def get_info(name, notfound_action=...):
        ...
    
    class lapack_opt_info(system_info):
        notfounderror = LapackNotFoundError
        def calc_info(self): # -> None:
            ...
        
    
    
    class blas_opt_info(system_info):
        notfounderror = BlasNotFoundError
        def calc_info(self): # -> None:
            ...
        
    
    
