"""
This type stub file was generated by pyright.
"""

from .minimize_trustregion_constr import _minimize_trustregion_constr

"""This module contains the equalit"""
__all__ = ['_minimize_trustregion_constr']
