"""
This type stub file was generated by pyright.
"""

"""Byrd-Omojokun Trust-Region SQP m"""
__all__ = ['equality_constrained_sqp']
def default_scaling(x): # -> csr_matrix | csc_matrix | coo_matrix | dia_matrix | Any:
    ...

def equality_constrained_sqp(fun_and_constr, grad_and_jac, lagr_hess, x0, fun0, grad0, constr0, jac0, stop_criteria, state, initial_penalty, initial_trust_radius, factorization_method, trust_lb=..., trust_ub=..., scaling=...):
    """Solve nonlinear equality-constra"""
    ...

