"""
This type stub file was generated by pyright.
"""

from .windows import *

"""
Window functions (:mod:`scipy.s"""
__all__ = ['boxcar', 'triang', 'parzen', 'bohman', 'blackman', 'nuttall', 'blackmanharris', 'flattop', 'bartlett', 'hanning', 'barthann', 'hamming', 'kaiser', 'gaussian', 'general_gaussian', 'general_cosine', 'general_hamming', 'chebwin', 'cosine', 'hann', 'exponential', 'tukey', 'taylor', 'get_window', 'dpss']
