"""
This type stub file was generated by pyright.
"""

"""
K-means clustering and vector q"""
__docformat__ = ...
__all__ = ['whiten', 'vq', 'kmeans', 'kmeans2']
class ClusterError(Exception):
    ...


def whiten(obs, check_finite=...): # -> Any:
    """
    Normalize a group of observ"""
    ...

def vq(obs, code_book, check_finite=...): # -> tuple[Any, Any]:
    """
    Assign codes from a code bo"""
    ...

def py_vq(obs, code_book, check_finite=...): # -> tuple[Any, Any]:
    """ Python version of vq algorithm."""
    ...

py_vq2 = ...
def kmeans(obs, k_or_guess, iter=..., thresh=..., check_finite=..., *, seed=...): # -> tuple[ndarray[Unknown, Unknown] | Unknown, float] | tuple[Unbound | ndarray[Unknown, Unknown] | Unknown, float]:
    """
    Performs k-means on a set o"""
    ...

_valid_init_meth = ...
_valid_miss_meth = ...
def kmeans2(data, k, iter=..., thresh=..., minit=..., missing=..., check_finite=..., *, seed=...): # -> tuple[ndarray[Unknown, Unknown] | Unknown | Any, Unbound | Unknown | Any]:
    """
    Classify a set of observati"""
    ...

