"""
This type stub file was generated by pyright.
"""

class _ScipyBackend:
    """The default backend for fft calc"""
    __ua_domain__ = ...
    @staticmethod
    def __ua_function__(method, args, kwargs): # -> _NotImplementedType | Any:
        ...
    


_named_backends = ...
def set_global_backend(backend): # -> None:
    """Sets the global fft backend

   """
    ...

def register_backend(backend): # -> None:
    """
    Register a backend for perm"""
    ...

def set_backend(backend, coerce=..., only=...):
    """Context manager to set the backe"""
    ...

def skip_backend(backend):
    """Context manager to skip a backen"""
    ...

