"""
This type stub file was generated by pyright.
"""

'''Fast Hankel transforms using the'''
__all__ = ['fht', 'ifht', 'fhtoffset']
LN_2 = ...
def fht(a, dln, mu, offset=..., bias=...):
    r'''Compute the fast Hankel transfor'''
    ...

def ifht(A, dln, mu, offset=..., bias=...):
    r'''Compute the inverse fast Hankel '''
    ...

def fhtcoeff(n, dln, mu, offset=..., bias=...): # -> ndarray[Unknown, Unknown]:
    '''Compute the coefficient array fo'''
    ...

def fhtoffset(dln, mu, initial=..., bias=...):
    '''Return optimal offset for a fast'''
    ...

