"""
This type stub file was generated by pyright.
"""

from ._basic import _dispatch

__all__ = ['dct', 'idct', 'dst', 'idst', 'dctn', 'idctn', 'dstn', 'idstn']
@_dispatch
def dctn(x, type=..., s=..., axes=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    """
    Return multidimensional Dis"""
    ...

@_dispatch
def idctn(x, type=..., s=..., axes=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    """
    Return multidimensional Dis"""
    ...

@_dispatch
def dstn(x, type=..., s=..., axes=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    """
    Return multidimensional Dis"""
    ...

@_dispatch
def idstn(x, type=..., s=..., axes=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    """
    Return multidimensional Dis"""
    ...

@_dispatch
def dct(x, type=..., n=..., axis=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    r"""Return the Discrete Cosine Trans"""
    ...

@_dispatch
def idct(x, type=..., n=..., axis=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    """
    Return the Inverse Discrete"""
    ...

@_dispatch
def dst(x, type=..., n=..., axis=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    r"""Return the Discrete Sine Transfo"""
    ...

@_dispatch
def idst(x, type=..., n=..., axis=..., norm=..., overwrite_x=..., workers=...): # -> tuple[Dispatchable]:
    """
    Return the Inverse Discrete"""
    ...

