"""
This type stub file was generated by pyright.
"""

def check_arguments(fun, y0, support_complex): # -> tuple[(t: Unknown, y: Unknown) -> ndarray[Unknown, Unknown], NDArray[Any]]:
    """Helper function for checking arg"""
    ...

class OdeSolver:
    """Base class for ODE solvers.

   """
    TOO_SMALL_STEP = ...
    def __init__(self, fun, t0, y0, t_bound, vectorized, support_complex=...) -> None:
        ...
    
    @property
    def step_size(self): # -> Any | None:
        ...
    
    def step(self): # -> None:
        """Perform one integration step.

 """
        ...
    
    def dense_output(self): # -> ConstantDenseOutput:
        """Compute a local interpolant over"""
        ...
    


class DenseOutput:
    """Base class for local interpolant"""
    def __init__(self, t_old, t) -> None:
        ...
    
    def __call__(self, t):
        """Evaluate the interpolant.

     """
        ...
    


class ConstantDenseOutput(DenseOutput):
    """Constant value interpolator.

  """
    def __init__(self, t_old, t, value) -> None:
        ...
    


