"""
This type stub file was generated by pyright.
"""

from .base import DenseOutput, OdeSolver

MAX_ORDER = ...
NEWTON_MAXITER = ...
MIN_FACTOR = ...
MAX_FACTOR = ...
def compute_R(order, factor): # -> ndarray[Unknown, Unknown]:
    """Compute the matrix for changing """
    ...

def change_D(D, order, factor): # -> None:
    """Change differences array in-plac"""
    ...

def solve_bdf_system(fun, t_new, y_predict, c, psi, LU, solve_lu, scale, tol):
    """Solve the algebraic system resul"""
    ...

class BDF(OdeSolver):
    """Implicit method based on backwar"""
    def __init__(self, fun, t0, y0, t_bound, max_step=..., rtol=..., atol=..., jac=..., jac_sparsity=..., vectorized=..., first_step=..., **extraneous) -> None:
        ...
    


class BdfDenseOutput(DenseOutput):
    def __init__(self, t_old, t, h, order, D) -> None:
        ...
    


