"""
This type stub file was generated by pyright.
"""

from scipy.optimize import OptimizeResult

METHODS = ...
MESSAGES = ...
class OdeResult(OptimizeResult):
    ...


def prepare_events(events): # -> tuple[tuple[Unknown] | Unknown, ndarray[Unknown, Unknown] | None, ndarray[Unknown, Unknown] | None]:
    """Standardize event functions and """
    ...

def solve_event_equation(event, sol, t_old, t): # -> tuple[Unknown, RootResults]:
    """Solve an equation corresponding """
    ...

def handle_events(sol, events, active_events, is_terminal, t_old, t): # -> tuple[Unknown, Any | ndarray[Unknown, Unknown], bool]:
    """Helper function to handle events"""
    ...

def find_active_events(g, g_new, direction): # -> ndarray[Unknown, Unknown]:
    """Find which event occurred during"""
    ...

def solve_ivp(fun, t_span, y0, method=..., t_eval=..., dense_output=..., events=..., vectorized=..., args=..., **options):
    """Solve an initial value problem f"""
    ...

