"""
This type stub file was generated by pyright.
"""

"""Compute the action of the matrix"""
__all__ = ['expm_multiply']
def expm_multiply(A, B, start=..., stop=..., num=..., endpoint=...):
    """
    Compute the action of the m"""
    ...

_theta = ...
class LazyOperatorNormInfo:
    """
    Information about an operat"""
    def __init__(self, A, A_1_norm=..., ell=..., scale=...) -> None:
        """
        Provide the operator an"""
        ...
    
    def set_scale(self, scale): # -> None:
        """
        Set the scale parameter"""
        ...
    
    def onenorm(self):
        """
        Compute the exact 1-nor"""
        ...
    
    def d(self, p):
        """
        Lazily estimate d_p(A) """
        ...
    
    def alpha(self, p):
        """
        Lazily compute max(d(p)"""
        ...
    


