"""
This type stub file was generated by pyright.
"""

"""Sparse block 1-norm estimator.
"""
__all__ = ['onenormest']
def onenormest(A, t=..., itmax=..., compute_v=..., compute_w=...): # -> tuple[Any | Unknown, ndarray[Unknown, Unknown] | Unknown, Any | Unknown] | tuple[Any | Unknown, Any | Unknown] | tuple[Any | Unknown, ndarray[Unknown, Unknown] | Unknown] | tuple[Any | Unknown] | Any:
    """
    Compute a lower bound of th"""
    ...

@_blocked_elementwise
def sign_round_up(X):
    """
    This should do the right th"""
    ...

def elementary_vector(n, i): # -> ndarray[Unknown, Unknown]:
    ...

def vectors_are_parallel(v, w):
    ...

def every_col_of_X_is_parallel_to_a_col_of_Y(X, Y): # -> bool:
    ...

def column_needs_resampling(i, X, Y=...): # -> bool:
    ...

def resample_column(i, X): # -> None:
    ...

def less_than_or_close(a, b): # -> Literal[True]:
    ...

