"""
This type stub file was generated by pyright.
"""

from .kdtree import *
from .ckdtree import *
from .qhull import *
from ._spherical_voronoi import SphericalVoronoi
from ._plotutils import *
from ._procrustes import procrustes
from ._geometric_slerp import geometric_slerp
from . import distance, transform
from scipy._lib._testutils import PytestTester

"""
==============================="""
__all__ = [s for s in dir() if nots.startswith('_')]
__all__ += ['distance', 'transform']
test = ...
