"""
This type stub file was generated by pyright.
"""

__all__ = ['geometric_slerp']
def geometric_slerp(start, end, t, tol=...): # -> ndarray[Unknown, Unknown]:
    """
    Geometric spherical linear """
    ...

