"""
This type stub file was generated by pyright.
"""

__all__ = ['delaunay_plot_2d', 'convex_hull_plot_2d', 'voronoi_plot_2d']
@_held_figure
def delaunay_plot_2d(tri, ax=...):
    """
    Plot the given Delaunay tri"""
    ...

@_held_figure
def convex_hull_plot_2d(hull, ax=...):
    """
    Plot the given convex hull """
    ...

@_held_figure
def voronoi_plot_2d(vor, ax=..., **kw):
    """
    Plot the given Voronoi diag"""
    ...

