"""
This type stub file was generated by pyright.
"""

"""
This module provides functions """
__all__ = ['procrustes']
def procrustes(data1, data2): # -> tuple[Unknown, Unknown, Any]:
    r"""Procrustes analysis, a similarit"""
    ...

