"""
This type stub file was generated by pyright.
"""

"""
Spherical Voronoi Code

.. vers"""
__all__ = ['SphericalVoronoi']
def calculate_solid_angles(R): # -> Any:
    """Calculates the solid angles of p"""
    ...

class SphericalVoronoi:
    """ Voronoi diagrams on the surface"""
    def __init__(self, points, radius=..., center=..., threshold=...) -> None:
        ...
    
    def sort_vertices_of_regions(self): # -> None:
        """Sort indices of the vertices to """
        ...
    
    def calculate_areas(self): # -> Any:
        """Calculates the areas of the Voro"""
        ...
    


