"""
This type stub file was generated by pyright.
"""

__all__ = ['odeint']
class ODEintWarning(Warning):
    ...


_msgs = ...
def odeint(func, y0, t, args=..., Dfun=..., col_deriv=..., full_output=..., ml=..., mu=..., rtol=..., atol=..., tcrit=..., h0=..., hmax=..., hmin=..., ixpr=..., mxstep=..., mxhnil=..., mxordn=..., mxords=..., printmessg=..., tfirst=...):
    """
    Integrate a system of ordin"""
    ...

