"""
This type stub file was generated by pyright.
"""

from .rotation import Rotation, Slerp
from ._rotation_spline import RotationSpline
from scipy._lib._testutils import PytestTester

"""
Spatial Transformations (:mod:`"""
__all__ = ['Rotation', 'Slerp', 'RotationSpline']
test = ...
