"""
This type stub file was generated by pyright.
"""

class RotationSpline:
    """Interpolate rotations with conti"""
    MAX_ITER = ...
    TOL = ...
    def __init__(self, times, rotations) -> None:
        ...
    
    def __call__(self, times, order=...): # -> Any:
        """Compute interpolated values.

  """
        ...
    


