"""
This type stub file was generated by pyright.
"""

"""
Laplacian of a compressed-spars"""
def laplacian(csgraph, normed=..., return_diag=..., use_out_degree=...): # -> tuple[Unknown, Unknown]:
    """
    Return the Laplacian matrix"""
    ...

