"""
This type stub file was generated by pyright.
"""

from .optimize import *
from ._minimize import *
from ._root import *
from ._root_scalar import *
from .minpack import *
from .zeros import *
from .lbfgsb import LbfgsInvHessProduct, fmin_l_bfgs_b
from .tnc import fmin_tnc
from .cobyla import fmin_cobyla
from .nonlin import *
from .slsqp import fmin_slsqp
from ._nnls import nnls
from ._basinhopping import basinhopping
from ._linprog import linprog, linprog_verbose_callback
from ._lsap import linear_sum_assignment
from ._differentialevolution import differential_evolution
from ._lsq import least_squares, lsq_linear
from ._constraints import Bounds, LinearConstraint, NonlinearConstraint
from ._hessian_update_strategy import BFGS, HessianUpdateStrategy, SR1
from ._shgo import shgo
from ._dual_annealing import dual_annealing
from ._qap import quadratic_assignment
from scipy._lib._testutils import PytestTester

"""
==============================="""
__all__ = [s for s in dir() if nots.startswith('_')]
test = ...
