"""
This type stub file was generated by pyright.
"""

"""Hessian update strategies for qu"""
__all__ = ['HessianUpdateStrategy', 'BFGS', 'SR1']
class HessianUpdateStrategy:
    """Interface for implementing Hessi"""
    def initialize(self, n, approx_type):
        """Initialize internal matrix.

   """
        ...
    
    def update(self, delta_x, delta_grad):
        """Update internal matrix.

       """
        ...
    
    def dot(self, p):
        """Compute the product of the inter"""
        ...
    
    def get_matrix(self):
        """Return current internal matrix.
"""
        ...
    


class FullHessianUpdateStrategy(HessianUpdateStrategy):
    """Hessian update strategy with ful"""
    _syr = ...
    _syr2 = ...
    _symv = ...
    def __init__(self, init_scale=...) -> None:
        ...
    
    def initialize(self, n, approx_type): # -> None:
        """Initialize internal matrix.

   """
        ...
    
    def update(self, delta_x, delta_grad): # -> None:
        """Update internal matrix.

       """
        ...
    
    def dot(self, p):
        """Compute the product of the inter"""
        ...
    
    def get_matrix(self):
        """Return the current internal matr"""
        ...
    


class BFGS(FullHessianUpdateStrategy):
    """Broyden-Fletcher-Goldfarb-Shanno"""
    def __init__(self, exception_strategy=..., min_curvature=..., init_scale=...) -> None:
        ...
    


class SR1(FullHessianUpdateStrategy):
    """Symmetric-rank-1 Hessian update """
    def __init__(self, min_denominator=..., init_scale=...) -> None:
        ...
    


