"""
This type stub file was generated by pyright.
"""

"""
A top-level linear programming """
__all__ = ['linprog', 'linprog_verbose_callback', 'linprog_terse_callback']
__docformat__ = ...
LINPROG_METHODS = ...
def linprog_verbose_callback(res): # -> None:
    """
    A sample callback function """
    ...

def linprog_terse_callback(res): # -> None:
    """
    A sample callback function """
    ...

def linprog(c, A_ub=..., b_ub=..., A_eq=..., b_eq=..., bounds=..., method=..., callback=..., options=..., x0=...):
    r"""
    Linear programming: minimiz"""
    ...

