"""
This type stub file was generated by pyright.
"""

"""
Unified interfaces to minimizat"""
__all__ = ['minimize', 'minimize_scalar']
MINIMIZE_METHODS = ...
MINIMIZE_SCALAR_METHODS = ...
def minimize(fun, x0, args=..., method=..., jac=..., hess=..., hessp=..., bounds=..., constraints=..., tol=..., callback=..., options=...):
    """Minimization of scalar function """
    ...

def minimize_scalar(fun, bracket=..., bounds=..., args=..., method=..., tol=..., options=...):
    """Minimization of scalar function """
    ...

def standardize_bounds(bounds, x0, meth): # -> Bounds | list[tuple[float | None, float | None]]:
    """Converts bounds to the form requ"""
    ...

def standardize_constraints(constraints, x0, meth): # -> list[NonlinearConstraint | LinearConstraint | dict[Unknown, Unknown]]:
    """Converts constraints to the form"""
    ...

