"""
This type stub file was generated by pyright.
"""

"""Routines for numerical different"""
def group_columns(A, order=...):
    """Group columns of a 2-D matrix fo"""
    ...

def approx_derivative(fun, x0, method=..., rel_step=..., abs_step=..., f0=..., bounds=..., sparsity=..., as_linear_operator=..., args=..., kwargs=...):
    """Compute finite difference approx"""
    ...

def check_derivative(fun, jac, x0, bounds=..., args=..., kwargs=...):
    """Check correctness of a function """
    ...

