"""
This type stub file was generated by pyright.
"""

QUADRATIC_ASSIGNMENT_METHODS = ...
def quadratic_assignment(A, B, method=..., options=...):
    r"""
    Approximates solution to th"""
    ...

