"""
This type stub file was generated by pyright.
"""

"""
Unified interfaces to root find"""
__all__ = ['root_scalar']
ROOT_SCALAR_METHODS = ...
class MemoizeDer:
    """Decorator that caches the value """
    def __init__(self, fun) -> None:
        ...
    
    def __call__(self, x, *args):
        r"""Calculate f or use cached value """
        ...
    
    def fprime(self, x, *args):
        r"""Calculate f' or use a cached val"""
        ...
    
    def fprime2(self, x, *args):
        r"""Calculate f'' or use a cached va"""
        ...
    
    def ncalls(self): # -> int:
        ...
    


def root_scalar(f, args=..., method=..., bracket=..., fprime=..., fprime2=..., x0=..., x1=..., xtol=..., rtol=..., maxiter=..., options=...):
    """
    Find a root of a scalar fun"""
    ...

