"""
This type stub file was generated by pyright.
"""

"""
Unified interfaces to root find"""
__all__ = ['root']
ROOT_METHODS = ...
def root(fun, x0, args=..., method=..., jac=..., tol=..., callback=..., options=...):
    """
    Find a root of a vector fun"""
    ...

