"""
This type stub file was generated by pyright.
"""

from ._trustregion import BaseQuadraticSubproblem

"""Dog-leg trust-region optimizatio"""
__all__ = []
class DoglegSubproblem(BaseQuadraticSubproblem):
    """Quadratic subproblem solved by t"""
    def cauchy_point(self):
        """
        The Cauchy point is min"""
        ...
    
    def newton_point(self):
        """
        The Newton point is a g"""
        ...
    
    def solve(self, trust_radius): # -> tuple[Unknown, Literal[False]] | tuple[Unknown, Literal[True]]:
        """
        Minimize a function usi"""
        ...
    


