"""
This type stub file was generated by pyright.
"""

from ._trustregion import BaseQuadraticSubproblem

"""Newton-CG trust-region optimizat"""
__all__ = []
class CGSteihaugSubproblem(BaseQuadraticSubproblem):
    """Quadratic subproblem solved by a"""
    def solve(self, trust_radius): # -> tuple[Unknown, Literal[False]] | tuple[Unknown, Literal[True]]:
        """
        Solve the subproblem us"""
        ...
    


