"""
This type stub file was generated by pyright.
"""

from threading import RLock

"""
Interface to Constrained Optimi"""
__all__ = ['fmin_cobyla']
_module_lock = RLock()
def synchronized(func): # -> (*args: Unknown, **kwargs: Unknown) -> Unknown:
    ...

@synchronized
def fmin_cobyla(func, x0, cons, args=..., consargs=..., rhobeg=..., rhoend=..., maxfun=..., disp=..., catol=...):
    """
    Minimize a function using t"""
    ...

