"""
This type stub file was generated by pyright.
"""

"""
Functions
---------
.. autosumm"""
__all__ = ['LineSearchWarning', 'line_search_wolfe1', 'line_search_wolfe2', 'scalar_search_wolfe1', 'scalar_search_wolfe2', 'line_search_armijo']
class LineSearchWarning(RuntimeWarning):
    ...


def line_search_wolfe1(f, fprime, xk, pk, gfk=..., old_fval=..., old_old_fval=..., args=..., c1=..., c2=..., amax=..., amin=..., xtol=...): # -> tuple[Any | None, int, int, Any | Unknown, Unknown, Unknown]:
    """
    As `scalar_search_wolfe1` b"""
    ...

def scalar_search_wolfe1(phi, derphi, phi0=..., old_phi0=..., derphi0=..., c1=..., c2=..., amax=..., amin=..., xtol=...): # -> tuple[Any | None, Any | Unknown, Unknown]:
    """
    Scalar function search for """
    ...

line_search = ...
def line_search_wolfe2(f, myfprime, xk, pk, gfk=..., old_fval=..., old_old_fval=..., args=..., c1=..., c2=..., amax=..., extra_condition=..., maxiter=...): # -> tuple[Unknown, int, int, Unknown, Unknown, Unknown | None]:
    """Find alpha that satisfies strong"""
    ...

def scalar_search_wolfe2(phi, derphi, phi0=..., old_phi0=..., derphi0=..., c1=..., c2=..., amax=..., extra_condition=..., maxiter=...):
    """Find alpha that satisfies strong"""
    ...

def line_search_armijo(f, xk, pk, gfk, old_fval, args=..., c1=..., alpha0=...): # -> tuple[int | Unknown | None, int, Unknown]:
    """Minimize over alpha, the functio"""
    ...

def line_search_BFGS(f, xk, pk, gfk, old_fval, args=..., c1=..., alpha0=...): # -> tuple[int | Unknown | None, int, Literal[0], Unknown]:
    """
    Compatibility wrapper for `"""
    ...

def scalar_search_armijo(phi, phi0, derphi0, c1=..., alpha0=..., amin=...): # -> tuple[int, Unknown] | tuple[Unknown, Unknown] | tuple[None, Unknown]:
    """Minimize over alpha, the functio"""
    ...

