"""
This type stub file was generated by pyright.
"""

error = ...
__all__ = ['fsolve', 'leastsq', 'fixed_point', 'curve_fit']
def fsolve(func, x0, args=..., fprime=..., full_output=..., col_deriv=..., xtol=..., maxfev=..., band=..., epsfcn=..., factor=..., diag=...): # -> tuple[Unknown, dict[str, Unknown | None], Unknown, Unknown]:
    """
    Find the roots of a functio"""
    ...

LEASTSQ_SUCCESS = ...
LEASTSQ_FAILURE = ...
def leastsq(func, x0, args=..., Dfun=..., full_output=..., col_deriv=..., ftol=..., xtol=..., gtol=..., maxfev=..., epsfcn=..., factor=..., diag=...):
    """
    Minimize the sum of squares"""
    ...

def curve_fit(f, xdata, ydata, p0=..., sigma=..., absolute_sigma=..., check_finite=..., bounds=..., method=..., jac=..., **kwargs):
    """
    Use non-linear least square"""
    ...

def check_gradient(fcn, Dfcn, x0, args=..., col_deriv=...): # -> tuple[Any, ndarray[Unknown, Unknown]]:
    """Perform a simple check on the gr"""
    ...

def fixed_point(func, x0, args=..., xtol=..., maxiter=..., method=...): # -> ndarray[Unknown, Unknown]:
    """
    Find a fixed point of the f"""
    ...

