"""
This type stub file was generated by pyright.
"""

from .stats import *
from .distributions import *
from .morestats import *
from ._binomtest import binomtest
from ._binned_statistic import *
from .kde import gaussian_kde
from . import contingency, mstats, qmc
from ._multivariate import *
from .contingency import chi2_contingency
from ._bootstrap import bootstrap
from ._entropy import *
from ._hypotests import *
from ._rvs_sampling import NumericalInverseHermite, rvs_ratio_uniforms
from ._page_trend_test import page_trend_test
from ._mannwhitneyu import mannwhitneyu
from scipy._lib._testutils import PytestTester

"""
.. _statsrefmanual:

=========="""
__all__ = [s for s in dir() if nots.startswith("_")]
test = ...
