"""
This type stub file was generated by pyright.
"""

class BinomTestResult:
    """
    Result of `scipy.stats.bino"""
    def __init__(self, k, n, alternative, pvalue, proportion_estimate) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def proportion_ci(self, confidence_level=..., method=...): # -> ConfidenceInterval:
        """
        Compute the confidence """
        ...
    


def binomtest(k, n, p=..., alternative=...): # -> BinomTestResult:
    """
    Perform a test that the pro"""
    ...

