"""
This type stub file was generated by pyright.
"""

__all__ = ['binned_statistic', 'binned_statistic_2d', 'binned_statistic_dd']
BinnedStatisticResult = ...
def binned_statistic(x, values, statistic=..., bins=..., range=...): # -> BinnedStatisticResult:
    """
    Compute a binned statistic """
    ...

BinnedStatistic2dResult = ...
def binned_statistic_2d(x, y, values, statistic=..., bins=..., range=..., expand_binnumbers=...): # -> BinnedStatistic2dResult:
    """
    Compute a bidimensional bin"""
    ...

BinnedStatisticddResult = ...
def binned_statistic_dd(sample, values, statistic=..., bins=..., range=..., expand_binnumbers=..., binned_statistic_result=...):
    """
    Compute a multidimensional """
    ...

