"""
This type stub file was generated by pyright.
"""

fields = ...
BootstrapResult = ...
def bootstrap(data, statistic, *, vectorized=..., paired=..., axis=..., confidence_level=..., n_resamples=..., batch=..., method=..., random_state=...): # -> Any:
    r"""
    Compute a two-sided bootstr"""
    ...

