"""
This type stub file was generated by pyright.
"""

def crosstab(*args, levels=..., sparse=...): # -> tuple[tuple[Unknown] | list[Unknown], coo_matrix | ndarray[Unknown, Unknown]]:
    """
    Return table of counts for """
    ...

