"""
This type stub file was generated by pyright.
"""

class _MWU:
    '''Distribution of MWU statistic un'''
    def __init__(self) -> None:
        '''Minimal initializer'''
        ...
    
    def pmf(self, k, m, n): # -> Any:
        '''Probability mass function'''
        ...
    
    def cdf(self, k, m, n): # -> Any:
        '''Cumulative distribution function'''
        ...
    
    def sf(self, k, m, n): # -> Any:
        '''Survival function'''
        ...
    


_mwu_state = ...
MannwhitneyuResult = ...
def mannwhitneyu(x, y, use_continuity=..., alternative=..., axis=..., method=...): # -> MannwhitneyuResult:
    r'''Perform the Mann-Whitney U rank '''
    ...

