"""
This type stub file was generated by pyright.
"""

def rvs_ratio_uniforms(pdf, umax, vmin, vmax, size=..., c=..., random_state=...): # -> ndarray[Unknown, Unknown]:
    """
    Generate random samples fro"""
    ...

class NumericalInverseHermite:
    r"""
    A Hermite spline fast numer"""
    def __init__(self, dist, *, tol=..., max_intervals=...) -> None:
        ...
    
    def ppf(self, q): # -> ndarray[Unknown, Unknown]:
        r"""
        Approximate percent poi"""
        ...
    
    def rvs(self, size=..., random_state=...): # -> ndarray[Unknown, Unknown]:
        """
        Random variates of the """
        ...
    
    def qrvs(self, size=..., d=..., qmc_engine=...):
        """
        Quasi-random variates o"""
        ...
    


