"""
This type stub file was generated by pyright.
"""

__all__ = ['_find_repeats', 'linregress', 'theilslopes', 'siegelslopes']
LinregressResult = ...
def linregress(x, y=..., alternative=...):
    """
    Calculate a linear least-sq"""
    ...

def theilslopes(y, x=..., alpha=...): # -> tuple[Unknown, Unknown, Unknown | Any, Unknown | Any]:
    r"""
    Computes the Theil-Sen esti"""
    ...

def siegelslopes(y, x=..., method=...): # -> tuple[Unknown, Unknown]:
    r"""
    Computes the Siegel estimat"""
    ...

