"""
This type stub file was generated by pyright.
"""

"""
Contingency table functions (:m"""
__all__ = ['margins', 'expected_freq', 'chi2_contingency', 'crosstab', 'association', 'relative_risk']
def margins(a): # -> list[Unknown]:
    """Return a list of the marginal su"""
    ...

def expected_freq(observed): # -> Any:
    """
    Compute the expected freque"""
    ...

def chi2_contingency(observed, correction=..., lambda_=...): # -> tuple[float | Unknown, float | Unknown, Any, Any]:
    """Chi-square test of independence """
    ...

def association(observed, method=..., correction=..., lambda_=...): # -> float:
    """Calculates degree of association"""
    ...

