"""
This type stub file was generated by pyright.
"""

__all__ = ['ldl']
def ldl(A, lower=..., hermitian=..., overwrite_a=..., check_finite=...): # -> tuple[ndarray[Unknown, Unknown], ndarray[Unknown, Unknown], ndarray[Unknown, Unknown]] | tuple[Unknown, Unknown, Unknown]:
    """ Computes the LDLt or Bunch-Kauf"""
    ...

