"""
This type stub file was generated by pyright.
"""

__all__ = ['qz', 'ordqz']
_double_precision = ...
def qz(A, B, output=..., lwork=..., sort=..., overwrite_a=..., overwrite_b=..., check_finite=...): # -> tuple[Unknown, Unknown, Unknown, Unknown]:
    """
    QZ decomposition for genera"""
    ...

def ordqz(A, B, sort=..., output=..., overwrite_a=..., overwrite_b=..., check_finite=...): # -> tuple[Unknown, Unknown, Unknown, Unknown, Unknown, Unknown]:
    """QZ decomposition for a pair of m"""
    ...

