"""
This type stub file was generated by pyright.
"""

__all__ = ['cossin']
def cossin(X, p=..., q=..., separate=..., swap_sign=..., compute_u=..., compute_vh=...):
    """
    Compute the cosine-sine (CS"""
    ...

