"""
This type stub file was generated by pyright.
"""

import numpy as np

"""
Matrix square root for general """
__all__ = ['sqrtm']
class SqrtmError(np.linalg.LinAlgError):
    ...


def sqrtm(A, disp=..., blocksize=...):
    """
    Matrix square root.

    Pa"""
    ...

