"""
This type stub file was generated by pyright.
"""

"""
Solve the orthogonal Procrustes"""
__all__ = ['orthogonal_procrustes']
def orthogonal_procrustes(A, B, check_finite=...): # -> tuple[Unknown, Unknown]:
    """
    Compute the matrix solution"""
    ...

