"""
This type stub file was generated by pyright.
"""

""" Sketching-based Matrix Computat"""
__all__ = ['clarkson_woodruff_transform']
def cwt_matrix(n_rows, n_columns, seed=...): # -> csc_matrix:
    r"""
    Generate a matrix S which r"""
    ...

def clarkson_woodruff_transform(input_matrix, sketch_size, seed=...):
    r"""
    Applies a Clarkson-Woodruff"""
    ...

