"""
This type stub file was generated by pyright.
"""

from scipy.linalg._fblas import *

"""
Low-level BLAS functions (:mod:"""
__all__ = ['get_blas_funcs', 'find_best_blas_type']
empty_module = ...
_type_score = ...
_type_conv = ...
_blas_alias = ...
def find_best_blas_type(arrays=..., dtype=...): # -> tuple[Literal['s', 'd', 'c', 'z'], dtype[float32] | dtype[float64] | dtype[complex64] | dtype[complex128], Unknown | bool]:
    """Find best-matching BLAS/LAPACK t"""
    ...

@_memoize_get_funcs
def get_blas_funcs(names, arrays=..., dtype=..., ilp64=...): # -> list[Unknown]:
    """Return available BLAS function o"""
    ...

