"""
This type stub file was generated by pyright.
"""

"""QR decomposition functions."""
__all__ = ['qr', 'qr_multiply', 'rq']
def safecall(f, name, *args, **kwargs):
    """Call a LAPACK routine, determini"""
    ...

def qr(a, overwrite_a=..., lwork=..., mode=..., pivoting=..., check_finite=...):
    """
    Compute QR decomposition of"""
    ...

def qr_multiply(a, c, mode=..., pivoting=..., conjugate=..., overwrite_a=..., overwrite_c=...):
    """
    Calculate the QR decomposit"""
    ...

def rq(a, overwrite_a=..., lwork=..., mode=..., check_finite=...):
    """
    Compute RQ decomposition of"""
    ...

