"""
This type stub file was generated by pyright.
"""

"""SVD decomposition functions."""
__all__ = ['svd', 'svdvals', 'diagsvd', 'orth', 'subspace_angles', 'null_space']
def svd(a, full_matrices=..., compute_uv=..., overwrite_a=..., check_finite=..., lapack_driver=...): # -> tuple[Unknown, Unknown, Unknown]:
    """
    Singular Value Decompositio"""
    ...

def svdvals(a, overwrite_a=..., check_finite=...): # -> tuple[Unknown, Unknown, Unknown] | ndarray[Unknown, Unknown]:
    """
    Compute singular values of """
    ...

def diagsvd(s, M, N): # -> Any:
    """
    Construct the sigma matrix """
    ...

def orth(A, rcond=...):
    """
    Construct an orthonormal ba"""
    ...

def null_space(A, rcond=...):
    """
    Construct an orthonormal ba"""
    ...

def subspace_angles(A, B):
    r"""
    Compute the subspace angles"""
    ...

