"""
This type stub file was generated by pyright.
"""

"""Cholesky decomposition functions"""
__all__ = ['cholesky', 'cho_factor', 'cho_solve', 'cholesky_banded', 'cho_solve_banded']
def cholesky(a, lower=..., overwrite_a=..., check_finite=...): # -> ndarray[Unknown, Unknown]:
    """
    Compute the Cholesky decomp"""
    ...

def cho_factor(a, lower=..., overwrite_a=..., check_finite=...): # -> tuple[ndarray[Unknown, Unknown] | Unknown, bool]:
    """
    Compute the Cholesky decomp"""
    ...

def cho_solve(c_and_lower, b, overwrite_b=..., check_finite=...):
    """Solve the linear equations A x ="""
    ...

def cholesky_banded(ab, overwrite_ab=..., lower=..., check_finite=...):
    """
    Cholesky decompose a banded"""
    ...

def cho_solve_banded(cb_and_lower, b, overwrite_b=..., check_finite=...):
    """
    Solve the linear equations """
    ...

