"""
This type stub file was generated by pyright.
"""

import numpy
from numpy import single

"""Schur decomposition functions."""
__all__ = ['schur', 'rsf2csf']
_double_precision = ...
def schur(a, output=..., lwork=..., overwrite_a=..., sort=..., check_finite=...):
    """
    Compute Schur decomposition"""
    ...

eps = numpy.finfo(float).eps
feps = numpy.finfo(single).eps
_array_kind = ...
_array_precision = ...
_array_type = ...
def rsf2csf(T, Z, check_finite=...): # -> tuple[Unknown | Any, Unknown | Any]:
    """
    Convert real Schur form to """
    ...

