"""
This type stub file was generated by pyright.
"""

"""LU decomposition functions."""
__all__ = ['lu', 'lu_solve', 'lu_factor']
def lu_factor(a, overwrite_a=..., check_finite=...): # -> tuple[Unknown, Unknown]:
    """
    Compute pivoted LU decompos"""
    ...

def lu_solve(lu_and_piv, b, trans=..., overwrite_b=..., check_finite=...):
    """Solve an equation system, a x = """
    ...

def lu(a, permute_l=..., overwrite_a=..., check_finite=...): # -> tuple[Unknown, Unknown] | tuple[Unknown, Unknown, Unknown]:
    """
    Compute pivoted LU decompos"""
    ...

