"""
This type stub file was generated by pyright.
"""

__all__ = ['LinAlgError', 'LinAlgWarning', 'norm']
class LinAlgWarning(RuntimeWarning):
    """
    The warning emitted when a """
    ...


def norm(a, ord=..., axis=..., keepdims=..., check_finite=...):
    """
    Matrix or vector norm.

   """
    ...

