"""
This type stub file was generated by pyright.
"""

__all__ = ['gcrotmk']
def gcrotmk(A, b, x0=..., tol=..., maxiter=..., M=..., callback=..., m=..., k=..., CU=..., discard_C=..., truncate=..., atol=...):
    """
    Solve a matrix equation usi"""
    ...

