"""
This type stub file was generated by pyright.
"""

__all__ = ['lgmres']
def lgmres(A, b, x0=..., tol=..., maxiter=..., M=..., callback=..., inner_m=..., outer_k=..., outer_v=..., store_outer_Av=..., prepend_outer_v=..., atol=...):
    """
    Solve a matrix equation usi"""
    ...

