"""
This type stub file was generated by pyright.
"""

"""
Copyright (C) 2010 David Fong a"""
__all__ = ['lsmr']
def lsmr(A, b, damp=..., atol=..., btol=..., conlim=..., maxiter=..., show=..., x0=...):
    """Iterative solver for least-squar"""
    ...

