"""
This type stub file was generated by pyright.
"""

import numpy as np

"""Sparse Equations and Least Squar"""
__all__ = ['lsqr']
eps = np.finfo(np.float64).eps
def lsqr(A, b, damp=..., atol=..., btol=..., conlim=..., iter_lim=..., show=..., calc_var=..., x0=...):
    """Find the least-squares solution """
    ...

