"""
This type stub file was generated by pyright.
"""

__docformat__ = ...
__all__ = []
_coerce_rules = ...
def coerce(x, y): # -> str:
    ...

def id(x):
    ...

def make_system(A, M, x0, b):
    """Make a linear system Ax=b

    P"""
    ...

