"""
This type stub file was generated by pyright.
"""

"""Bounded-variable least-squares a"""
def compute_kkt_optimality(g, on_bound):
    """Compute the maximum violation of"""
    ...

def bvls(A, b, x_lsq, lb, ub, tol, max_iter, verbose, rcond=...):
    ...

