"""
This type stub file was generated by pyright.
"""

"""
Dogleg algorithm with rectangul"""
def lsmr_operator(Jop, d, active_set): # -> LinearOperator:
    """Compute LinearOperator to use in"""
    ...

def find_intersection(x, tr_bounds, lb, ub): # -> tuple[Any, Any, Any, Any, Any, Any]:
    """Find intersection of trust-regio"""
    ...

def dogleg_step(x, newton_step, g, a, b, tr_bounds, lb, ub): # -> tuple[Unknown, ndarray[Unknown, Unknown], Literal[False]] | tuple[Unknown, ndarray[Unknown, Unknown], bool_]:
    """Find dogleg step in a rectangula"""
    ...

def dogbox(fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale, loss_function, tr_solver, tr_options, verbose):
    ...

