"""
This type stub file was generated by pyright.
"""

"""Linear least squares with bound """
def prepare_bounds(bounds, n): # -> tuple[ndarray[Unknown, Unknown], ndarray[Unknown, Unknown]]:
    ...

TERMINATION_MESSAGES = ...
def lsq_linear(A, b, bounds=..., method=..., tol=..., lsq_solver=..., lsmr_tol=..., max_iter=..., verbose=...):
    r"""Solve a linear least-squares pro"""
    ...

