"""
This type stub file was generated by pyright.
"""

__all__ = ['fourier_gaussian', 'fourier_uniform', 'fourier_ellipsoid', 'fourier_shift']
def fourier_gaussian(input, sigma, n=..., axis=..., output=...): # -> ndarray[Unknown, Unknown]:
    """
    Multidimensional Gaussian f"""
    ...

def fourier_uniform(input, size, n=..., axis=..., output=...): # -> ndarray[Unknown, Unknown]:
    """
    Multidimensional uniform fo"""
    ...

def fourier_ellipsoid(input, size, n=..., axis=..., output=...): # -> ndarray[Unknown, Unknown]:
    """
    Multidimensional ellipsoid """
    ...

def fourier_shift(input, shift, n=..., axis=..., output=...): # -> ndarray[Unknown, Unknown]:
    """
    Multidimensional Fourier sh"""
    ...

