"""
This type stub file was generated by pyright.
"""

from ._ni_docstrings import docfiller

__all__ = ['spline_filter1d', 'spline_filter', 'geometric_transform', 'map_coordinates', 'affine_transform', 'shift', 'zoom', 'rotate']
@docfiller
def spline_filter1d(input, order=..., axis=..., output=..., mode=...):
    """
    Calculate a 1-D spline filt"""
    ...

def spline_filter(input, order=..., output=..., mode=...):
    """
    Multidimensional spline fil"""
    ...

@docfiller
def geometric_transform(input, mapping, output_shape=..., output=..., order=..., mode=..., cval=..., prefilter=..., extra_arguments=..., extra_keywords=...):
    """
    Apply an arbitrary geometri"""
    ...

@docfiller
def map_coordinates(input, coordinates, output=..., order=..., mode=..., cval=..., prefilter=...):
    """
    Map the input array to new """
    ...

@docfiller
def affine_transform(input, matrix, offset=..., output_shape=..., output=..., order=..., mode=..., cval=..., prefilter=...):
    """
    Apply an affine transformat"""
    ...

@docfiller
def shift(input, shift, output=..., order=..., mode=..., cval=..., prefilter=...):
    """
    Shift an array.

    The ar"""
    ...

@docfiller
def zoom(input, zoom, output=..., order=..., mode=..., cval=..., prefilter=..., *, grid_mode=...):
    """
    Zoom an array.

    The arr"""
    ...

@docfiller
def rotate(input, angle, axes=..., reshape=..., output=..., order=..., mode=..., cval=..., prefilter=...):
    """
    Rotate an array.

    The a"""
    ...

