"""
This type stub file was generated by pyright.
"""

__all__ = ['label', 'find_objects', 'labeled_comprehension', 'sum', 'mean', 'variance', 'standard_deviation', 'minimum', 'maximum', 'median', 'minimum_position', 'maximum_position', 'extrema', 'center_of_mass', 'histogram', 'watershed_ift', 'sum_labels']
def label(input, structure=..., output=...):
    """
    Label features in an array."""
    ...

def find_objects(input, max_label=...):
    """
    Find objects in a labeled a"""
    ...

def labeled_comprehension(input, labels, index, func, out_dtype, default, pass_positions=...):
    """
    Roughly equivalent to [func"""
    ...

def sum(input, labels=..., index=...):
    """
    Calculate the sum of the va"""
    ...

def sum_labels(input, labels=..., index=...):
    """
    Calculate the sum of the va"""
    ...

def mean(input, labels=..., index=...):
    """
    Calculate the mean of the v"""
    ...

def variance(input, labels=..., index=...):
    """
    Calculate the variance of t"""
    ...

def standard_deviation(input, labels=..., index=...): # -> Any:
    """
    Calculate the standard devi"""
    ...

def minimum(input, labels=..., index=...):
    """
    Calculate the minimum of th"""
    ...

def maximum(input, labels=..., index=...):
    """
    Calculate the maximum of th"""
    ...

def median(input, labels=..., index=...):
    """
    Calculate the median of the"""
    ...

def minimum_position(input, labels=..., index=...): # -> tuple[Unknown, ...] | list[tuple[Unknown, ...]]:
    """
    Find the positions of the m"""
    ...

def maximum_position(input, labels=..., index=...): # -> tuple[Unknown, ...] | list[tuple[Unknown, ...]]:
    """
    Find the positions of the m"""
    ...

def extrema(input, labels=..., index=...): # -> tuple[Unknown, Unknown, tuple[Unknown, ...], tuple[Unknown, ...]] | tuple[Unknown, Unknown, list[tuple[Unknown, ...]], list[tuple[Unknown, ...]]]:
    """
    Calculate the minimums and """
    ...

def center_of_mass(input, labels=..., index=...): # -> tuple[Unknown, ...] | list[tuple[Any, ...]]:
    """
    Calculate the center of mas"""
    ...

def histogram(input, min, max, bins, labels=..., index=...):
    """
    Calculate the histogram of """
    ...

def watershed_ift(input, markers, structure=..., output=...):
    """
    Apply watershed from marker"""
    ...

